###
GET http://localhost:8080/dosis_values
Accept: application/json
###
GET http://localhost:8080/dosis_values/1
Accept: application/json

###
POST http://localhost:8080/dosis_values
Content-Type: application/json

{
    "dosis": "3",
    "date": "2022-10-10"
}
###
DELETE http://localhost:8080/dosis_values/102
###
PUT http://localhost:8080/dosis_values/1
Content-Type: application/json

{
  "id": "1",
  "inrValue": "3.2",
  "date": "2022-11-11"
}
